apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "svn.fullname" . }}
  labels:
{{- if .Values.subversion.labels }}
{{ toYaml .Values.subversion.labels | indent 4 }}
{{- end }}
  annotations:
    deployment.kubernetes.io/revision: "2"
spec:
  replicas: 1
  serviceName: {{ template "svn.fullname" . }}
  selector:
    matchLabels:
      app: subversion-edge
      release: svn
  template:
    metadata:
      labels:
        app: subversion-edge
        release: svn
    spec:
      containers:
      - env:
          - name: JAVA_HOME
            value: /usr/lib/jvm/java-8-openjdk-amd64
          - name: RUN_AS_USER
            value: collabnet
          - name: SU_OPTS
            value: "-m -s /bin/bash"
        name: {{ template "svn.name" . }}
        image: {{ .Values.subversion.imageName }}
        imagePullPolicy: IfNotPresent
        resources: {}         
        ports:
          - containerPort: 3343
            name: http-admin
          - containerPort: 4434
            name: https-admin
          - containerPort: 18080
            name: http-svn             
        volumeMounts:
          - mountPath: /opt/csvn/data
            name: svn-data
      volumes:
      - name: svn-data
        persistentVolumeClaim:
          claimName: {{ template "svn.fullname" . }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
